hw done
tikhcloud/hh-hw-psql pull request #1
Opened 2020-12-12 21:42 UTC by tikhcloud

2020-12-20 20:09 UTC, eldmitrieva requested changes

2020-12-20 20:09 UTC, eldmitrieva commented on query.sql
> +               INNER JOIN vacancy AS v
если у работодателя не было вакансий или откликов, то его в выборке не будет, надо поправить, чтобы был

2020-12-20 20:09 UTC, eldmitrieva commented on query.sql
> +      GROUP BY employer_name) AS nnor
разные работодатели могут иметь одинаковое название

2020-12-20 20:09 UTC, eldmitrieva commented on query.sql
> +SELECT area_name, min(r.created_on - v.created_on), max(r.created_on - v.created_on)
необходимо посчитать время до ПЕРВОГО отклика на вакансию

2020-12-20 20:54 UTC, eldmitrieva commented on query.sql
> +               INNER JOIN vacancy AS v
Случайно удалила комментарий, надо поправить join, чтобы работодатели без откликов тоже могли попасть в топ

2020-12-22 18:47 UTC, tikhcloud commented on query.sql
> +      GROUP BY e.employer_id) AS nnor
Исправил, считаю теперь response_id, а не все строки и использую LEFT JOIN, чтобы не отсекались работодатели без откликов

2020-12-22 18:47 UTC, tikhcloud commented on query.sql
> +SELECT area_name, min(response_time) AS min, max(response_time) AS max
Исправил, теперь считаю время до первого отклика

2020-12-23 09:09 UTC, eldmitrieva requested changes

2020-12-23 09:09 UTC, eldmitrieva commented on query.sql
> +WHERE v.compensation_gross IS NULL
а где проверка на наличие зарплаты?

2020-12-23 14:10 UTC, tikhcloud commented on query.sql
> +WHERE v.compensation_gross IS NULL
Исправил, но логика была такова, что если `compensation_to` И `compensation_from` **NULL**, то тогда и `compensation_gross` тоже **NULL**.
<img width="976" alt="dataGrip_screen" src="https://user-images.githubusercontent.com/57270287/103003343-ac400680-4541-11eb-8bb2-e1e34cc0f23f.png">

2020-12-23 15:01 UTC, eldmitrieva commented on query.sql
> +WHERE v.compensation_gross IS NULL
Так можно было бы сделать, если бы было ограничение в базе, что если compensation_gross = null, тогда и зарплата тоже null. А так любой злодей может записать что угодно)

2020-12-23 15:04 UTC, eldmitrieva requested changes

2020-12-23 15:04 UTC, eldmitrieva commented on query.sql
> +      GROUP BY employer_name) AS evn ;
не надо группировать по названию компании, нет ограничений, что названия уникальны, так что может быть несколько компаний с одинаковым названием

2020-12-23 15:04 UTC, eldmitrieva commented on query.sql
> +GROUP BY area_name;
по названию города тоже группировать не надо, так как бывают города с одинаковым названием

2020-12-23 15:32 UTC, tikhcloud commented on query.sql
> +      GROUP BY employer_name) AS evn ;
Исправил, теперь сортирую по id

2020-12-23 15:32 UTC, tikhcloud commented on query.sql
> +GROUP BY area_name;
Исправил, теперь сортирую по id

2020-12-23 15:33 UTC, tikhcloud commented on query.sql
> +      GROUP BY employer_name) AS evn ;
Исправил, теперь группирую по id

2020-12-23 15:33 UTC, tikhcloud commented on query.sql
> +GROUP BY area_name;
Исправил, теперь группирую по id

2020-12-23 15:35 UTC, eldmitrieva approved these changes

2021-09-01 09:05 UTC, closed without merging